import axios from 'axios';
import { supabase } from '../database/db.js';

const LINKEDIN_API_URL = 'https://api.linkedin.com/v2';

export const postToLinkedIn = async (companyId, content) => {
    const { text, url, visibility = 'PUBLIC' } = content;

    // 1. Get Access Token
    const { data: account, error } = await supabase
        .from('social_accounts')
        .select('provider_account_id, access_token')
        .eq('company_id', companyId)
        .eq('provider', 'linkedin')
        .single();

    if (error || !account) {
        throw new Error('LinkedIn account not connected.');
    }

    const { provider_account_id, access_token } = account;

    // 2. Handle Image Upload if URL exists
    let assetUrn = null;
    if (url) {
        try {
            // A. Download Image
            const imageResponse = await axios.get(url, { responseType: 'arraybuffer' });
            const imageBuffer = imageResponse.data;
            const contentType = imageResponse.headers['content-type'];

            // B. Register Upload
            const registerResponse = await axios.post(`${LINKEDIN_API_URL}/assets?action=registerUpload`, {
                registerUploadRequest: {
                    recipes: ["urn:li:digitalmediaRecipe:feedshare-image"],
                    owner: `urn:li:person:${provider_account_id}`,
                    serviceRelationships: [{
                        relationshipType: "OWNER",
                        identifier: "urn:li:userGeneratedContent"
                    }]
                }
            }, {
                headers: {
                    'Authorization': `Bearer ${access_token}`,
                    'X-Restli-Protocol-Version': '2.0.0',
                    'Content-Type': 'application/json'
                }
            });

            const uploadUrl = registerResponse.data.value.uploadMechanism['com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest'].uploadUrl;
            assetUrn = registerResponse.data.value.asset;

            // C. Upload Binary
            await axios.put(uploadUrl, imageBuffer, {
                headers: {
                    'Authorization': `Bearer ${access_token}`,
                    'Content-Type': contentType || 'application/octet-stream' // Important to match
                }
            });
            // D. Wait for completion (LinkedIn can be slow)

        } catch (uploadError) {
            console.error('Failed to upload image to LinkedIn:', uploadError.message);
            // Fallback: Just append URL to text if upload fails
            text += `\n\n${url}`;
        }
    }

    // 3. Construct Payload
    // Docs: https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api
    const payload = {
        author: `urn:li:person:${provider_account_id}`,
        lifecycleState: 'PUBLISHED',
        specificContent: {
            "com.linkedin.ugc.ShareContent": {
                shareCommentary: {
                    text: text
                },
                shareMediaCategory: assetUrn ? "IMAGE" : "NONE",
                media: assetUrn ? [{
                    status: "READY",
                    description: { text: "Generated by StartupLab Content Generator" },
                    media: assetUrn,
                    title: { text: "Post Image" }
                }] : []
            }
        },
        visibility: {
            "com.linkedin.ugc.MemberNetworkVisibility": visibility
        }
    };

    // If no assetUrn but url exists (fallback happened), we already appended it to text above.
    // If no assetUrn and no url, it's a text-only post (NONE).

    try {
        const response = await axios.post(`${LINKEDIN_API_URL}/ugcPosts`, payload, {
            headers: {
                'Authorization': `Bearer ${access_token}`,
                'X-Restli-Protocol-Version': '2.0.0',
                'Content-Type': 'application/json'
            }
        });
        return response.data;
    } catch (err) {
        console.error('LinkedIn final post error:', err.response?.data || err.message);
        throw new Error(`LinkedIn publish failed: ${err.response?.data?.message || err.message}`);
    }
};

/**
 * Publishes a post to a Facebook Page.
 * @param {string} companyId 
 * @param {object} content { text, url }
 */
export const postToFacebookPage = async (companyId, content) => {
    const { text, url } = content;

    // 1. Get Page Access Token and Page ID from DB
    const { data: account, error } = await supabase
        .from('social_accounts')
        .select('provider_account_id, access_token')
        .eq('company_id', companyId)
        .eq('provider', 'facebook')
        .single(); // Note: If multiple pages are allowed, this needs adjustment or selection logic.
    // For now, assuming the single() match for MVP, or we pass the specific provider_account_id if needed.

    if (error || !account) {
        throw new Error('Facebook Page account not connected or found.');
    }

    const { provider_account_id: pageId, access_token: pageAccessToken } = account;
    const FB_GRAPH_URL = `https://graph.facebook.com/v18.0/${pageId}`;

    try {
        let response;
        if (url) {
            // Posting with Image
            response = await axios.post(`${FB_GRAPH_URL}/photos`, {
                url: url,
                message: text,
                access_token: pageAccessToken
            });
        } else {
            // Text-only post
            response = await axios.post(`${FB_GRAPH_URL}/feed`, {
                message: text,
                access_token: pageAccessToken
            });
        }

        return response.data;

    } catch (err) {
        console.error('Facebook Page publish error:', err.response?.data || err.message);
        throw new Error(`Facebook publish failed: ${err.response?.data?.error?.message || err.message}`);
    }
};

/**
 * Fetches insights for a specific Facebook post.
 * @param {string} companyId 
 * @param {string} postId The Facebook post ID (global ID)
 * @returns {object} { reach, likes, comments }
 */
export const getFacebookPostInsights = async (companyId, postId) => {
    // 1. Get Page Access Token from DB
    const { data: account, error } = await supabase
        .from('social_accounts')
        .select('access_token')
        .eq('company_id', companyId)
        .eq('provider', 'facebook')
        .single();

    if (error || !account) {
        throw new Error('Facebook account not connected.');
    }

    const { access_token } = account;

    // 2. Fetch Insights
    // post_impressions_unique = Reach
    // summary(true) for likes and comments
    const FB_GRAPH_URL = `https://graph.facebook.com/v18.0/${postId}`;

    try {
        const [insightsRes, countsRes] = await Promise.all([
            axios.get(`${FB_GRAPH_URL}/insights?metric=post_impressions_unique&access_token=${access_token}`),
            axios.get(`${FB_GRAPH_URL}?fields=likes.summary(true),comments.summary(true)&access_token=${access_token}`)
        ]);

        const reach = insightsRes.data.data?.[0]?.values?.[0]?.value || 0;
        const likes = countsRes.data.likes?.summary?.total_count || 0;
        const comments = countsRes.data.comments?.summary?.total_count || 0;

        return {
            reach,
            likes,
            comments
        };
    } catch (err) {
        console.error('Facebook insights error:', err.response?.data || err.message);
        throw new Error(`Failed to fetch Facebook insights: ${err.response?.data?.error?.message || err.message}`);
    }
};
